### ISSUE TITLE
用docker-compose加载

### ISSUE THREAD

**Issue by lencshu** [pch18-docker/baota#29]
请问这个得如何在docker-compose里面运行？我尝试过，但是错误提示：

> /entrypoint.sh: line 6: bt: command not found

yml配置如下，该怎么改进呢？

```yml
version: '3'

services:
  
  lap:
    container_name: baota-lap
    image: pch18/baota:lap
    ports:
        - "80:80"
        - "443:443" 
        - "8888:8888"
        - "888:888" 
        - "20:20" 
        - "21:21"
    privileged: true
    volumes:
        - ./baota:/www
        - ./codes:/www/wwwroot
    restart: always
```

其中./codes里面是网站代码
./baota里面是宝塔的配置
